#page title
page-title                                : "Berserk Studios"                                        

# App Info
ios-app-id                                : ""                               

appstore-link                             : https://apps.apple.com/us/app/itunes-remote/id284417350                                         
playstore-link                            : https://play.google.com/store/apps/details?id=air.au.com.metro.DumbWaysToDie2
presskit-title                            : Press Kit
presskit-download-link                    : https://developer.apple.com/app-store/marketing/guidelines/#images
                                                                                  

app-icon                                  : assets/appicon.png                   
app-name                                  : App connect                             
app-price                                 : Free                                    
app-description                           : Write a short tagline for your app.

enable-smart-app-banner                   : true                                    

# Information About Yourself
footer-description                          : Made by John Doe in New York
contact-list:
- url: "mailto:john.doe@gmail.com"
  icon: envelope
- url: https://twitter.com/john.doe
  icon: twitter
- url: https://github.com/john.doe
  icon: github


# Feature List                            Edit, add or remove features to be presented.
features-list                             :

  - title                                 : GitHub Pages Jekyll Theme
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome-icon-name                 : magic
    
  - title                                 : iPhone Device Preview
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome-icon-name                 : mobile

  - title                                 : Video Support
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome-icon-name                 : play-circle

  - title                                 : Automatic Icon and Metadata
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome-icon-name                 : refresh

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome-icon-name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome-icon-name                 : star

  - title                                 : Smart App Banner
    description                           : Display a smart app banner on iOS devices.
    fontawesome-icon-name                 : arrow-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome-icon-name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome-icon-name                 : info



# Theme Settings
topbar-color                              : "#000000"
topbar-transparency                       : "0.1"
topbar-title-color                        : "#ffffff"

cover-image                               : assets/headerimage.png             
cover-overlay-color                       : "#363b3d"
cover-overlay-transparency                : "0.8"

device-color                              : black                              

body-background-color                     : "#ffffff"

link-color                                : "#1d63ea"

app-title-color                           : "#ffffff"
app-price-color                           : "#ffffff"
app-description-color                     : "#ffffff"

feature-title-color                       : "#000000"
feature-text-color                        : "#666666"

feature-icons-foreground-color            : "#1d63ea"
feature-icons-background-color            : "#e6e6e6"

social-icons-foreground-color             : "#666666"
social-icons-background-color             : "#e6e6e6"

footer-text-color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
# exclude:
#   - LICENSE
#   - README.md
#   - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
